wamprouter:
  image: semiot/wamp-router:v1.0.6
  links:
    - mysqlbase
  ports:
    - "8080:8080"
  restart: always

dataarchivingservice:
  image: semiot/data-archiving-service:v1.0.6
  links:
    - tsdb
    - wamprouter
    - deviceproxyservice
    - fuseki
  ports:
    - "8787:8787"
  volumes:
    - /semiot-platform/data-archiving-service/:/semiot-platform/data-archiving-service/
  restart: always

tsdb:
  image: cassandra:3.3
  ports:
    - "9042:9042"
  volumes:
    - /semiot-platform/tsdb:/var/lib/cassandra
  restart: always

deviceproxyservice:
  image: semiot/device-proxy-service:v1.0.6
  links:
    - wamprouter
    - fuseki
  ports:
    - "8181:8181"
    - "9500:9500/udp"
    - "3131:3131/udp"
  volumes:
    - /semiot-platform/felix-cache:/root/semiot-platform/device-proxy-service/felix-cache
  restart: always

fuseki:
  image: semiot/fuseki:v1.0.6
  ports:
    - "3030:3030"
  volumes:
    - /semiot-platform/fuseki/fuseki-db:/fuseki/fuseki-db
    - /semiot-platform/fuseki/app:/fuseki/app
  restart: always

apigateway:
  image: semiot/api-gateway:v1.0.6
  links:
    - wamprouter
    - deviceproxyservice
    - dataarchivingservice
    - mysqlbase
    - fuseki
  ports:
    - "8383:8080"
    - "9990:9990"
  volumes:
    - /semiot-platform/api-gateway/:/semiot-platform/api-gateway/
  restart: always

frontend:
  image: semiot/frontend:v1.0.6
  links:
    - wamprouter
    - deviceproxyservice
    - apigateway
  ports:
    - "80:80"
  restart: always

mysqlbase:
  image: semiot/mysql:v1.0.6
  ports:
    - "3306:3306"
  restart: always
