wamprouter:
  image: docker.semiot.ru/wamp-router
  ports:
    - "8080:8080"
  restart: always

devicedirectoryservice:
  image: docker.semiot.ru/device-directory-service
  links:
    - wamprouter
  ports:
    - "3030:3030"
  volumes:
    - /semiot-platform/fuseki/base:/fuseki/base
  restart: always

dataarchivingservice:
  image: docker.semiot.ru/data-archiving-service
  links:
    - opentsdb
    - wamprouter
    - devicedirectoryservice
  volumes:
    - /semiot-platform/data-archiving-service/:/semiot-platform/data-archiving-service/
  restart: always
  
opentsdb:
  image: docker.semiot.ru/opentsdb-docker
  ports:
    - "4242:4242"
  volumes:
    - /etc/opentsdb:/etc/opentsdb
    - /semiot-platform/opentsdb/data/hbase:/data/hbase
  restart: always

webui:
  image: docker.semiot.ru/web-ui
  ports:
    - "80:80"
  restart: always

deviceproxyservice:
  image: docker.semiot.ru/device-proxy-service
  links:
    - wamprouter
  ports:
    - "8181:8181"
    - "9500:9500/udp"
    - "3131:3131/udp"
  volumes:
    - /semiot-platform/felix-cache:/root/semiot-platform/device-proxy-service/felix-cache
  restart: always

analyzingservice:
  image: docker.semiot.ru/analysing-service
  links:
    - wamprouter
  ports:
    - "8085:8085"
  volumes:
    - /semiot-platform/analysing-service/:/semiot-platform/analysing-service/
  restart: always
