wamprouter:
  image: docker.semiot.ru/wamp-router
  ports:
    - "8080:8080"
  restart: always

dataarchivingservice:
  image: docker.semiot.ru/data-archiving-service
  links:
    - opentsdb
    - wamprouter
    - deviceproxyservice
  volumes:
    - /semiot-platform/data-archiving-service/:/semiot-platform/data-archiving-service/
  restart: always
  
opentsdb:
  image: docker.semiot.ru/opentsdb
  links:
    - hbase
  ports:
    - "4242:4242"
  command: bash -c "echo \"tsd.http.request.cors_domains=*\" > /etc/opentsdb/opentsdb.conf && echo \"tsd.core.meta.enable_realtime_ts=True\" >> /etc/opentsdb/opentsdb.conf && sh /opt/run.sh"
  volumes:
    - /etc/opentsdb:/etc/opentsdb
  restart: always

webui:
  image: docker.semiot.ru/web-ui
  ports:
    - "80:80"
  restart: always

deviceproxyservice:
  image: docker.semiot.ru/device-proxy-service
  links:
    - wamprouter
  ports:
    - "8181:8181"
    - "3030:3030"
    - "9500:9500/udp"
    - "3131:3131/udp"
  volumes:
    - /semiot-platform/felix-cache:/root/semiot-platform/device-proxy-service/felix-cache
    - /semiot-platform/fuseki/fuseki-db:/fuseki/fuseki-db
  restart: always
  
  hbase:
  image: docker.semiot.ru/hbase
  ports:
    - "60000:60000"
    - "60010:60010"
    - "60020:60020"
    - "60030:60030"
    - "2181:2181"
  volumes:
    - /semiot-platform/hbase/logs/:/opt/hbase/logs/
    - /semiot-platform/hbase/data/:/etc/hbase
  restart: always
