deviceproxyservice:
  image: semiot/device-proxy-service
  links:
    - wamprouter
  ports:
    - "3131:3131/udp"
  restart: always

devicedirectoryservice:
  image: semiot/device-directory-service
  links:
    - wamprouter
  ports:
    - "3030:3030"
  restart: always

dataarchivingservice:
  image: semiot/data-archiving-service
  links:
      - opentsdb
  restart: always

opentsdb:
  image: petergrace/opentsdb-docker
  ports:
      - "4242:4242"
  restart: always

wamprouter:
  image: semiot/wamp-router
  ports:
    - "80:80"
  restart: always

webui:
  image: semiot/web-ui
  ports:
    - "8080:80"
  restart: always
