wamprouter:
  image: semiot/wamp-router:v1.0.5
  ports:
    - "8080:8080"
  restart: always

dataarchivingservice:
  image: semiot/data-archiving-service:v1.0.5
  links:
    - opentsdb
    - wamprouter
    - deviceproxyservice
  ports:
    - "8787:8787"
  volumes:
    - /semiot-platform/data-archiving-service/:/semiot-platform/data-archiving-service/
  restart: always
  
opentsdb:
  image: semiot/opentsdb:v1.0.5
  links:
    - hbase
  ports:
    - "4242:4242"
  volumes:
    - /etc/opentsdb:/etc/opentsdb
  restart: always

webui:
  image: semiot/web-ui:v1.0.5
  ports:
    - "8484:80"
  restart: always

deviceproxyservice:
  image: semiot/device-proxy-service:v1.0.5
  links:
    - wamprouter
  ports:
    - "8181:8181"
    - "3030:3030"
    - "9500:9500/udp"
    - "3131:3131/udp"
  volumes:
    - /semiot-platform/felix-cache:/root/semiot-platform/device-proxy-service/felix-cache
    - /semiot-platform/fuseki/fuseki-db:/fuseki/fuseki-db
    - /semiot-platform/fuseki/app:/fuseki/app
    - /semiot-platform/device-proxy-service/proxy-logs:/root/semiot-platform/device-proxy-service/proxy-logs
  restart: always
  
hbase:
  image: semiot/hbase:v1.0.5
  ports:
    - "60000:60000"
    - "60010:60010"
    - "60020:60020"
    - "60030:60030"
    - "2181:2181"
  volumes:
    - /semiot-platform/hbase/logs/:/opt/hbase/logs/
    - /semiot-platform/hbase/data/:/etc/hbase
  restart: always

apigateway:
  image: semiot/api-gateway:v1.0.5
  links:
    - wamprouter
    - opentsdb
    - deviceproxyservice
    - dataarchivingservice
    - mysqlbase
  ports:
    - "8383:8080"
    - "9990:9990"
  volumes:
    - /semiot-platform/api-gateway/:/semiot-platform/api-gateway/
  restart: always

frontend:
  image: semiot/frontend:v1.0.5
  links:
    - wamprouter
    - deviceproxyservice
    - webui
    - apigateway
  ports:
    - "80:80"
  restart: always

mysqlbase:
  image: semiot/mysql:v1.0.5
  ports:
    - "3306:3306"
  restart: always
