wamprouter:
  image: semiot/wamp-router:v1.0.0
  ports:
    - "8080:8080"
  restart: always

devicedirectoryservice:
  image: semiot/device-directory-service:v1.0.0
  links:
    - wamprouter
  ports:
    - "3030:3030"
  volumes:
    - /semiot-platform/fuseki/fuseki-db:/fuseki/fuseki-db
  restart: always

dataarchivingservice:
  image: semiot/data-archiving-service:v1.0.0
  links:
    - opentsdb
    - wamprouter
    - devicedirectoryservice
  volumes:
    - /semiot-platform/data-archiving-service/:/semiot-platform/data-archiving-service/
  restart: always
  
opentsdb:
  image: semiot/opentsdb-docker:v1.0.0
  ports:
    - "4242:4242"
  volumes:
    - /etc/opentsdb:/etc/opentsdb
    - /semiot-platform/opentsdb/data/hbase:/data/hbase
  restart: always

webui:
  image: semiot/web-ui:v1.0.0
  ports:
    - "80:80"
  restart: always

deviceproxyservice:
  image: semiot/device-proxy-service:v1.0.0
  links:
    - wamprouter
    - devicedirectoryservice
  ports:
    - "8181:8181"
    - "9500:9500/udp"
    - "3131:3131/udp"
  volumes:
    - /semiot-platform/felix-cache:/root/semiot-platform/device-proxy-service/felix-cache
  restart: always
