wamprouter:
  image: semiot/wamp-router
  ports:
    - "8080:8080"
  restart: always

devicedirectoryservice:
  image: semiot/device-directory-service
  links:
    - wamprouter
  ports:
    - "3030:3030"
  restart: always

dataarchivingservice:
  image: semiot/data-archiving-service
  links:
      - opentsdb
      - wamprouter
  volumes:
      - /semiot-platform/data-archiving-service/:/semiot-platform/data-archiving-service/
  restart: always
  
opentsdb:
  image: semiot/opentsdb-docker
  ports:
      - "4242:4242"
  volumes:
      - /etc/opentsdb:/etc/opentsdb
  restart: always

webui:
  image: semiot/web-ui
  ports:
    - "80:80"
  restart: always

deviceproxyservice:
  image: semiot/device-proxy-service
  links:
    - wamprouter
  ports:
    - "8181:8181"
    - "9500:9500/udp"
    - "3131:3131/udp"
  restart: always

analyzingservice:
  image: semiot/analyzing-service
  links:
    - wamprouter
  ports:
    - "8085:8085"
  restart: always
