wamprouter:
  image: semiot/wamp-router:v0.1.0-rc.7
  links:
    - mysqlbase
  restart: always

dataarchivingservice:
  image: semiot/data-archiving-service:v0.1.0-rc.7
  links:
    - tsdb
    - wamprouter
    - deviceproxyservice
    - triplestore
  volumes:
    - /semiot-platform/data-archiving-service/:/semiot-platform/data-archiving-service/
  restart: always

tsdb:
  image: cassandra:3.3
  volumes:
    - /semiot-platform/tsdb:/var/lib/cassandra
  restart: always

deviceproxyservice:
  image: semiot/device-proxy-service:v0.1.0-rc.7
  links:
    - wamprouter
    - triplestore
  ports:
    - "9500:9500/udp"
    - "3131:3131/udp"
  volumes:
    - /semiot-platform/felix-cache:/root/semiot-platform/device-proxy-service/felix-cache
    - /semiot-platform/device-proxy-service:/semiot-platform/device-proxy-service
  extra_hosts:
    - "assets-cdn.github.com:151.101.12.133"
    - "raw.githubusercontent.com:151.101.12.133"
  restart: always

triplestore:
  image: semiot/triplestore:v0.1.0-rc.7
  restart: always

apigateway:
  image: semiot/api-gateway:v0.1.0-rc.7
  links:
    - wamprouter
    - deviceproxyservice
    - dataarchivingservice
    - mysqlbase
    - triplestore
  volumes:
    - /semiot-platform/api-gateway/:/semiot-platform/api-gateway/
  extra_hosts:
    - "assets-cdn.github.com:151.101.12.133"
    - "raw.githubusercontent.com:151.101.12.133"
  restart: always

frontend:
  image: semiot/frontend:v0.1.0-rc.7
  links:
    - wamprouter
    - deviceproxyservice
    - apigateway
  ports:
    - "80:80"
    - "443:443"
  restart: always

mysqlbase:
  image: semiot/mysql:v0.1.0-rc.7
  restart: always
