opentsdb:
    image: petergrace/opentsdb-docker
    ports:
        - "4242:4242"
    restart: always

dataarchivingservice:
    image: semiot/data-archiving-service
    links:
        - opentsdb
    restart: always
